# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
# set -g window-status-current-format ''
# set -g window-status-format ''

set-option -g default-shell /bin/zsh
## Clipboard integration
# ctrl+c to send to clipboard
bind C-c run "tmux save-buffer - | xclip -i -sel clipboard"
# ctrl+v to paste from clipboard
bind C-v run "tmux set-buffer \"$(xclip -o -sel clipboard)\"; tmux paste-buffer"
# THEME
set -g default-terminal "xterm-256color:RGB"
set -g set-clipboard on
# set -as terminal-features "xterm-256color:RGB"
# set -as terminal-overrides ',*:sitm=\E[3m'
# set -as terminal-overrides ',*:ritm=\E[23m'
#set -g window-status-current-style bg=white, fg=black, attr=bold
set-window-option -g window-status-current-style fg=black,bg=white
# set -g status-interval 60
# set -g status-left-length 30
# set -g status-left '#[fg=green](#S) #(whoami)'
# set -g status-right '#[fg=yellow]#(cut -d " " -f 1-3 /proc/loadavg)#[default] #[fg=white]%H:%M#[default]'
# set -g focus-events on
# set -g status-style bg=default
# set -g status-left-length 99
# set -g status-right-length 99
# set -g status-justify absolute-centre
set -g focus-events on
set -g status-style "bg=default, fg=green"
set -g window-status-separator ""
# set -g status-left '#(cat #{socket_path}-\#{session_id}-vimbridge)'
set -g status-left-length 99
# set -g status-right '#(cat #{socket_path}-\#{session_id}-vimbridge-R)'
set -g status-right-length 99
setw -g window-status-format "#[fg=black,bg=#bbbbbb]  #I:#W #[default]"
setw -g window-status-current-format "#[fg=white,bg=#333333,bold] #I:#W #[default]"
# setw -g window-status-format "#[fg=black,bg=#dddddd] #[fg=black,bg=#dddddd] #I:#W #[fg=#dddddd,bg=default,nobold] "
# setw -g window-status-current-format "#[fg=#ffffff,bg=#5f87ff,bold] #[fg=#ffffff,bg=#5f87ff] #I:#W #[fg=#5f87ff,bg=default] "
set -g status-justify absolute-centre
set-option -g status-left "#[align=centre,bg=default,fg=black]#[bg=#555555,fg=white,bold] #S #[bg=default,fg=#555555]"
set -g status-right " #[fg=#000000,bg=#bbbbbb] %Y-%m-%d #[fg=#bbbbbb,bg=#999999] #[fg=#ffffff,bg=#999999] %H:%M #[fg=#999999,bg=#5f5f87] #[fg=#5f5f87,bg=default] #[fg=white]#(hostname -s)"
# Tmux Plugin Manager
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Save/Restore session plugins
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'

# Initialize Tmux Plugin Manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
